# Generated by Django 6.0.1 on 2026-02-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_total_amount_orders_totel_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='totel_amount',
        ),
    ]
