# Generated by Django 6.0.1 on 2026-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orders_totel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totel_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
