# Generated by Django 6.0.1 on 2026-02-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image1_product_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='img2',
        ),
    ]
