# Generated by Django 6.0.1 on 2026-02-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image1_product_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img3_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img4_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
