# Generated by Django 6.0.1 on 2026-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_img3_url_product_img4_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img3_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img4_url',
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
